version: '3.7'
services:
    mirakurun:
        build:
            context: mirakurun
        container_name: mirakurun
        #cap_add:
        #    - SYS_NICE
        #    - SYS_ADMIN
        privileged: true
        ports:
            - "40772:40772"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mirakurun/conf:/usr/local/etc/mirakurun
            - ./mirakurun/db:/usr/local/var/db/mirakurun
        environment:
            TZ: "Asia/Tokyo"
        devices:
            - /dev/pt3video0:/dev/pt3video0
            - /dev/pt3video1:/dev/pt3video1
            - /dev/pt3video2:/dev/pt3video2
            - /dev/pt3video3:/dev/pt3video3
            #- /dev/bus/usb/00x/00x # card reader
        #restart: always

    mysql:
        image: mariadb:10.4
        container_name: mysql
        volumes:
            - mysql-db:/var/lib/mysql
        environment:
            MYSQL_USER: epgstation
            MYSQL_PASSWORD: epgstation
            MYSQL_ROOT_PASSWORD: epgstation
            MYSQL_DATABASE: epgstation
            TZ: "Asia/Tokyo"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --performance-schema=false --expire_logs_days=1
        #restart: always

    epgstation:
        build:
            context: epgstation
            args:
                - CPUCORE=2
        container_name: epgstation
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./epgstation/config:/app/config
            - ./epgstation/data:/app/data
            - ./epgstation/thumbnail:/app/thumbnail
            - ./epgstation/logs:/app/logs
            - ./recorded:/app/recorded
        environment:
            TZ: "Asia/Tokyo"
        links:
            - mirakurun:mirakurun
            - mysql:mysql
        ports:
            - "8888:8888"
            - "8889:8889"
        #user: "1000:1000"
        #restart: always

volumes:
    mysql-db:
        driver: local

